#!/bin/bash
#
# SMTPy Mail Server Testing Script
# Tests mail.smtpy.fr DNS configuration and SMTP connectivity
#
# Usage: ./test-mail-smtpy.sh
#

# Use gtimeout on macOS if available, otherwise use timeout, or skip
if command -v gtimeout &> /dev/null; then
    TIMEOUT_CMD="gtimeout"
elif command -v timeout &> /dev/null; then
    TIMEOUT_CMD="timeout"
else
    TIMEOUT_CMD=""
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SMTP_HOSTNAME="mail.atomdev.fr"
SMTP_PORT="25"
EXPECTED_IP="45.80.25.57"  # Update this with your actual server IP

echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}        SMTPy Mail Server Testing Script${NC}"
echo -e "${BLUE}        Testing: ${SMTP_HOSTNAME}${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}\n"

# Test counter
TESTS_PASSED=0
TESTS_FAILED=0

# Function to print test header
print_test() {
    echo -e "\n${YELLOW}[TEST]${NC} $1"
    echo "----------------------------------------"
}

# Function to print success
print_success() {
    echo -e "${GREEN}✓ PASS:${NC} $1"
    TESTS_PASSED=$((TESTS_PASSED + 1))
}

# Function to print failure
print_failure() {
    echo -e "${RED}✗ FAIL:${NC} $1"
    TESTS_FAILED=$((TESTS_FAILED + 1))
}

# Function to print info
print_info() {
    echo -e "${BLUE}ℹ INFO:${NC} $1"
}

# Function to print warning
print_warning() {
    echo -e "${YELLOW}⚠ WARNING:${NC} $1"
}

#
# Test 1: DNS A Record Resolution
#
print_test "1. DNS A Record Resolution"
A_RECORD=$(dig +short A ${SMTP_HOSTNAME} | tail -n1)
if [ -n "$A_RECORD" ]; then
    print_success "A record exists: ${SMTP_HOSTNAME} → ${A_RECORD}"
    if [ "$A_RECORD" == "$EXPECTED_IP" ]; then
        print_success "IP matches expected: ${EXPECTED_IP}"
    else
        print_warning "IP differs from expected. Got: ${A_RECORD}, Expected: ${EXPECTED_IP}"
    fi
else
    print_failure "No A record found for ${SMTP_HOSTNAME}"
fi

#
# Test 2: Reverse DNS (PTR) Record
#
print_test "2. Reverse DNS (PTR) Record"
if [ -n "$A_RECORD" ]; then
    PTR_RECORD=$(dig +short -x ${A_RECORD} | sed 's/\.$//')
    if [ -n "$PTR_RECORD" ]; then
        print_success "PTR record exists: ${A_RECORD} → ${PTR_RECORD}"
        if [ "$PTR_RECORD" == "$SMTP_HOSTNAME" ]; then
            print_success "PTR matches hostname perfectly"
        else
            print_warning "PTR doesn't match. Got: ${PTR_RECORD}, Expected: ${SMTP_HOSTNAME}"
        fi
    else
        print_failure "No PTR record found for ${A_RECORD}"
        print_info "Contact your hosting provider to set up reverse DNS"
    fi
else
    print_warning "Skipping PTR check (no A record)"
fi

#
# Test 3: MX Record for smtpy.fr
#
print_test "3. MX Record for smtpy.fr"
MX_RECORD=$(dig +short MX smtpy.fr)
if [ -n "$MX_RECORD" ]; then
    print_success "MX record exists for smtpy.fr:"
    echo "$MX_RECORD" | while read line; do
        print_info "  $line"
    done

    # Check if mail.smtpy.fr is in the MX records
    if echo "$MX_RECORD" | grep -q "mail.smtpy.fr"; then
        print_success "mail.smtpy.fr is configured as MX server"
    else
        print_warning "mail.smtpy.fr not found in MX records"
    fi
else
    print_failure "No MX record found for smtpy.fr"
fi

#
# Test 4: SPF Record
#
print_test "4. SPF Record for smtpy.fr"
SPF_RECORD=$(dig +short TXT smtpy.fr | grep "v=spf1" || echo "")
if [ -n "$SPF_RECORD" ]; then
    print_success "SPF record exists:"
    print_info "  $SPF_RECORD"

    # Check if it includes the mail server IP
    if echo "$SPF_RECORD" | grep -q "$EXPECTED_IP\|mail.smtpy.fr"; then
        print_success "SPF includes mail server"
    else
        print_warning "SPF might not include mail server IP/hostname"
    fi
else
    print_failure "No SPF record found for smtpy.fr"
    print_info "Add: v=spf1 ip4:${EXPECTED_IP} ~all"
fi

#
# Test 5: DMARC Record
#
print_test "5. DMARC Record for smtpy.fr"
DMARC_RECORD=$(dig +short TXT _dmarc.smtpy.fr | grep "v=DMARC1" || echo "")
if [ -n "$DMARC_RECORD" ]; then
    print_success "DMARC record exists:"
    print_info "  $DMARC_RECORD"
else
    print_failure "No DMARC record found"
    print_info "Add: v=DMARC1; p=quarantine; rua=mailto:dmarc@smtpy.fr"
fi

#
# Test 6: DKIM Record (default selector)
#
print_test "6. DKIM Record for smtpy.fr"
DKIM_RECORD=$(dig +short TXT default._domainkey.smtpy.fr | grep "v=DKIM1" || echo "")
if [ -n "$DKIM_RECORD" ]; then
    print_success "DKIM record exists (default selector):"
    print_info "  ${DKIM_RECORD:0:80}..."
else
    print_warning "No DKIM record found for default._domainkey.smtpy.fr"
    print_info "DKIM keys are generated by SMTPy after domain verification"
fi

#
# Test 7: SMTP Port Connectivity (Port 25)
#
print_test "7. SMTP Port 25 Connectivity"
if command -v nc &> /dev/null; then
    if nc -G 5 -zv ${A_RECORD:-$SMTP_HOSTNAME} 25 2>&1 | grep -q "succeeded\|open"; then
        print_success "Port 25 is open and accepting connections"
    else
        print_failure "Cannot connect to port 25"
        print_info "Check firewall rules: sudo ufw allow 25/tcp"
    fi
elif command -v telnet &> /dev/null; then
    if bash -c "echo quit | telnet ${A_RECORD:-$SMTP_HOSTNAME} 25" 2>&1 | grep -q "Connected\|220"; then
        print_success "Port 25 is open and accepting connections"
    else
        print_failure "Cannot connect to port 25"
    fi
else
    print_warning "Neither nc nor telnet available. Install with: apt-get install netcat"
fi

#
# Test 8: SMTP Banner Test
#
print_test "8. SMTP Server Banner"
if command -v nc &> /dev/null; then
    if [ -n "$TIMEOUT_CMD" ]; then
        BANNER=$($TIMEOUT_CMD 5 bash -c "echo QUIT | nc ${A_RECORD:-$SMTP_HOSTNAME} 25 2>/dev/null | head -n1" || echo "")
    else
        BANNER=$(echo QUIT | nc -G 5 ${A_RECORD:-$SMTP_HOSTNAME} 25 2>/dev/null | head -n1 || echo "")
    fi
    if [ -n "$BANNER" ]; then
        print_success "SMTP server responded:"
        print_info "  $BANNER"

        # Check if hostname matches
        if echo "$BANNER" | grep -q "$SMTP_HOSTNAME"; then
            print_success "Banner includes correct hostname"
        else
            print_warning "Banner might not include correct hostname"
        fi
    else
        print_failure "No SMTP banner received"
    fi
else
    print_warning "Skipping banner test (nc not available)"
fi

#
# Test 9: TLS/STARTTLS Support
#
print_test "9. STARTTLS Support"
if command -v openssl &> /dev/null; then
    if [ -n "$TIMEOUT_CMD" ]; then
        STARTTLS_CHECK=$($TIMEOUT_CMD 5 bash -c "echo QUIT | openssl s_client -starttls smtp -connect ${A_RECORD:-$SMTP_HOSTNAME}:25 -brief 2>&1" || true)
    else
        STARTTLS_CHECK=$(echo QUIT | openssl s_client -starttls smtp -connect ${A_RECORD:-$SMTP_HOSTNAME}:25 -brief 2>&1 || true)
    fi
    if echo "$STARTTLS_CHECK" | grep -q "250-STARTTLS\|250 STARTTLS"; then
        print_success "STARTTLS is supported"
    else
        print_warning "STARTTLS might not be enabled"
        print_info "Modern SMTP servers should support STARTTLS"
    fi
else
    print_warning "OpenSSL not available for TLS testing"
fi

#
# Test 10: Hostname Resolution Time
#
print_test "10. DNS Resolution Performance"
RESOLVE_TIME=$(dig ${SMTP_HOSTNAME} | grep "Query time:" | awk '{print $4}')
if [ -n "$RESOLVE_TIME" ]; then
    print_success "DNS resolution time: ${RESOLVE_TIME}ms"
    if [ "$RESOLVE_TIME" -lt 100 ]; then
        print_success "DNS resolution is fast (< 100ms)"
    elif [ "$RESOLVE_TIME" -lt 500 ]; then
        print_info "DNS resolution is acceptable (< 500ms)"
    else
        print_warning "DNS resolution is slow (> 500ms)"
    fi
fi

#
# Test 11: Check if server is blacklisted (basic check)
#
print_test "11. Basic Blacklist Check"
print_info "For comprehensive blacklist checking, visit:"
print_info "  • https://mxtoolbox.com/blacklists.aspx"
print_info "  • https://multirbl.valli.org/lookup/"
print_info "  • Enter IP: ${A_RECORD:-$EXPECTED_IP}"

#
# Test 12: SMTP Submission Port (587) - Optional
#
print_test "12. SMTP Submission Port 587 (Optional)"
if command -v nc &> /dev/null; then
    if nc -G 5 -zv ${A_RECORD:-$SMTP_HOSTNAME} 587 2>&1 | grep -q "succeeded\|open"; then
        print_success "Port 587 is open (submission port)"
    else
        print_info "Port 587 is not open (optional for relay)"
    fi
fi

#
# Test 13: Internal SMTP Port 1025 (for Docker)
#
print_test "13. Internal Docker SMTP Port 1025"
print_info "Port 1025 should NOT be publicly accessible"
if command -v nc &> /dev/null; then
    if nc -G 3 -zv ${A_RECORD:-$SMTP_HOSTNAME} 1025 2>&1 | grep -q "succeeded\|open"; then
        print_warning "Port 1025 is publicly accessible! This should be internal only."
        print_info "Check Docker port mappings in docker-compose"
    else
        print_success "Port 1025 is not publicly accessible (correct)"
    fi
fi

#
# Summary
#
echo -e "\n${BLUE}════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}                      TEST SUMMARY${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Tests Passed: ${TESTS_PASSED}${NC}"
echo -e "${RED}Tests Failed: ${TESTS_FAILED}${NC}"

if [ $TESTS_FAILED -eq 0 ]; then
    echo -e "\n${GREEN}✓ All critical tests passed!${NC}"
    echo -e "${GREEN}  Your mail server appears to be configured correctly.${NC}"
else
    echo -e "\n${YELLOW}⚠ Some tests failed or need attention.${NC}"
    echo -e "${YELLOW}  Review the failures above and consult the deployment guide.${NC}"
fi

echo -e "\n${BLUE}Additional Resources:${NC}"
print_info "Deployment Guide: docs/DEPLOYMENT_GUIDE.md"
print_info "SMTP Relay README: back/smtp/relay/README.md"
print_info "Test email delivery: https://www.mail-tester.com/"

echo -e "\n${BLUE}════════════════════════════════════════════════════════════${NC}\n"

exit 0
