"""Initial migration

Revision ID: 670fe8f48b87
Revises: 
Create Date: 2025-08-19 17:03:43.852756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670fe8f48b87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_event_type'), 'activity_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_log_status'), 'activity_log', ['status'], unique=False)
    op.create_index(op.f('ix_activity_log_timestamp'), 'activity_log', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=64), nullable=True),
    sa.Column('password_reset_expiry', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('subscription_status', sa.String(length=32), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_stripe_customer_id'), 'user', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_user_subscription_status'), 'user', ['subscription_status'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('catch_all', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_created_at'), 'domain', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_deleted_at'), 'domain', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_domain_is_deleted'), 'domain', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_domain_name'), 'domain', ['name'], unique=True)
    op.create_index(op.f('ix_domain_owner_id'), 'domain', ['owner_id'], unique=False)
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_created_at'), 'invitation', ['created_at'], unique=False)
    op.create_index(op.f('ix_invitation_email'), 'invitation', ['email'], unique=False)
    op.create_index(op.f('ix_invitation_expires_at'), 'invitation', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invitation_invited_by'), 'invitation', ['invited_by'], unique=False)
    op.create_index(op.f('ix_invitation_token'), 'invitation', ['token'], unique=True)
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_part', sa.String(length=100), nullable=False),
    sa.Column('targets', sa.String(length=1000), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'local_part', name='uix_alias_domain_local_part')
    )
    op.create_index(op.f('ix_alias_created_at'), 'alias', ['created_at'], unique=False)
    op.create_index(op.f('ix_alias_deleted_at'), 'alias', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_alias_domain_id'), 'alias', ['domain_id'], unique=False)
    op.create_index(op.f('ix_alias_expires_at'), 'alias', ['expires_at'], unique=False)
    op.create_index(op.f('ix_alias_is_deleted'), 'alias', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_alias_local_part'), 'alias', ['local_part'], unique=False)
    op.create_index(op.f('ix_alias_owner_id'), 'alias', ['owner_id'], unique=False)
    op.create_table('forwarding_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forwarding_rule_created_at'), 'forwarding_rule', ['created_at'], unique=False)
    op.create_index(op.f('ix_forwarding_rule_domain_id'), 'forwarding_rule', ['domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forwarding_rule_domain_id'), table_name='forwarding_rule')
    op.drop_index(op.f('ix_forwarding_rule_created_at'), table_name='forwarding_rule')
    op.drop_table('forwarding_rule')
    op.drop_index(op.f('ix_alias_owner_id'), table_name='alias')
    op.drop_index(op.f('ix_alias_local_part'), table_name='alias')
    op.drop_index(op.f('ix_alias_is_deleted'), table_name='alias')
    op.drop_index(op.f('ix_alias_expires_at'), table_name='alias')
    op.drop_index(op.f('ix_alias_domain_id'), table_name='alias')
    op.drop_index(op.f('ix_alias_deleted_at'), table_name='alias')
    op.drop_index(op.f('ix_alias_created_at'), table_name='alias')
    op.drop_table('alias')
    op.drop_index(op.f('ix_invitation_token'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_invited_by'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_expires_at'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_email'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_created_at'), table_name='invitation')
    op.drop_table('invitation')
    op.drop_index(op.f('ix_domain_owner_id'), table_name='domain')
    op.drop_index(op.f('ix_domain_name'), table_name='domain')
    op.drop_index(op.f('ix_domain_is_deleted'), table_name='domain')
    op.drop_index(op.f('ix_domain_deleted_at'), table_name='domain')
    op.drop_index(op.f('ix_domain_created_at'), table_name='domain')
    op.drop_table('domain')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_subscription_status'), table_name='user')
    op.drop_index(op.f('ix_user_stripe_customer_id'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_activity_log_timestamp'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_status'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_event_type'), table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
