"""add subscription_status to user

Revision ID: aa743f0ae8ca
Revises: 547f091366a6
Create Date: 2025-07-15 08:59:05.970409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa743f0ae8ca'
down_revision: Union[str, None] = '547f091366a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscription_status', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_subscription_status'), 'user', ['subscription_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscription_status'), table_name='user')
    op.drop_column('user', 'subscription_status')
    # ### end Alembic commands ###
